[package]
name = "terminal-transport-game"
version = "0.1.0"
authors = ["Vinermy <egorkosachev@vk.com>"]
license = "MIT"
edition = "2021"

[dependencies]
ratatui = "0.27.0"
specs = "0.16.1"
specs-derive = "0.4.1"
